memory_binding_setting: fix incorrect exception message
The first exception message is below:
avocado.core.exceptions.TestCancel: Expect 2 numa nodes at least, but found 1
But the final exception message is below.
AttributeError: 'NoneType' object has no attribute 'set_node_num_huge_pages'

The first exception is root cause , but overwritten by the final one. This is because
insufficient handling in teardown function.
This patch is a simple fix for this issue.

Signed-off-by: Dan Zheng <dzheng@redhat.com>