Handle date output format change
Recent distributions like Ubuntu 20.04, date command
output format changed, hence the below error,

ValueError: time data 'Sat 08 Feb 2020 01:00:25 IST' does not match format '%a %b %d %H:%M:%S %Y

So let's handle it by forcing the date command output with
a format string, though this can be generic for all distributions,
there may be some old distributions might not support format string
with date command, so let's handle it in failure path not to break
tests in other environments.

Signed-off-by: Satheesh Rajendran <sathnaga@linux.vnet.ibm.com>