auto_dump: replace process.kill with process.terminate
func 'kill' of multiprocessing.Process was brought in from python3.7
therefore not availabe on python3.6. Replacing with 'terminate' could
allow test running on python3.6 without throwing out error like:
`AttributeError: 'Process' object has no attribute 'kill'`

Signed-off-by: Haijiao Zhao <haizhao@redhat.com>