Fixup: incorrect module import for python3
Seems letters from string module is deprecated in python3, so below error
ERROR: cannot import name 'letters' from 'string' (/usr/lib/python3.8/string.py)

Let's fix it by changing it to supported one.

Signed-off-by: Satheesh Rajendran <sathnaga@linux.vnet.ibm.com>