v2v: delete 'ipconfig /renew' operation for windows checking
The 'ipconfig /renew' might change the IP address of the VM and
cause shell session disconnect.

The error is like below.
aexpect.exceptions.ShellProcessTerminatedError: Shell process terminated
while waiting for command to complete: 'ipconfig /renew'    (status: 1,
output: '\nWindows IP Configuration\n\nNcat: Connection reset by peer.\n')

Because not every ip renew will change the IP address, the problem may
happens occasionally. IMHO, this checkpoint is not necessary. The VM
has IP address and can be connected have already proved the network driver
is working well.

Signed-off-by: Xiaodai Wang <xiaodwan@redhat.com>