Update to start virtproxyd service
Check virtproxyd service on remote host to avoid following error:
virt-admin # uri
error: Failed to connect to the admin server
error: no valid connection
error: Failed to connect socket to
'/run/libvirt/libvirt-admin-sock': Connection refused

Signed-off-by: lcheng <lcheng@redhat.com>