migration: Fix a TypeError
Fix following issue:
  TypeError: setup_conn_obj() missing 1 required positional
  argument: 'test'

Signed-off-by: cliping <lcheng@redhat.com>