utils_misc: always update parameters in subclass_pre_init()
I tried to execute boot and netperf tests in one job,
but netperf which needs two nics failed and got this
error: "IndexError: list index out of range"

After executed boot subtest, vm class was restored into env file,
in the second test, cloned VMNet class has attributes (vm_name,
params, container_class), so the parameters could not be updated.

This patch makes parameters can be updated all the time.

Signed-off-by: Amos Kong <akong@redhat.com>