migration: Fix rng issue
Fix following issue:
  DeviceNotRemovedError: Error in phase POST_MIGRATE_BACK:Device
  rng is not removed from vm

tpm device also has a buitin rng device, so after detaching rng
device, we can still see /dev/hwrng in vm. So need to remove tpm
device from vm xml.

Signed-off-by: cliping <lcheng@redhat.com>