Fix script error for "console_target_type_virtio"
Fix following error msg caused by two 'None' type variables
in re.match(exp_ser_dev, ser_dev) when testing virtio console
TypeError: first argument must be string or compiled pattern&#10;

Signed-off-by: jiyan <jiyan@redhat.com>