hotplug_serial: fix 'unknown device type'
Error while running it on RHEL6.7 Beta.

02:54:30 DEBUG| Running virsh command: attach-device vm1
/home/autotest/client/tests/virt/tmp/hotplug_serial/xml_pty
02:54:30 DEBUG| Running '/usr/bin/virsh attach-device vm1
/home/autotest/client/tests/virt/tmp/hotplug_serial/xml_pty'
02:54:30 DEBUG| status: 1
02:54:30 DEBUG| stdout:
02:54:30 DEBUG| stderr: error:
Failed to attach device from
/home/autotest/client/tests/virt/tmp/hotplug_serial/xml_pty
error: XML error: unknown device type

In fact, serial device is supported since 1.1.1.
It's necessary to check the result of attach-device command.