usb_device: Fix the unassigned variable 'usb_cmd'
Fixes the regression from 1a20a4a3a. It will cause this error for
non-redirect device caes:

UnboundLocalError: cannot access local variable 'usb_cmd' where it is not associated with a value

Signed-off-by: Han Han <hhan@redhat.com>