virsh_domxml_from_native: use complete qemu binary path for parse it to virsh
It happens that `cat -v /proc/<qemu_pid>/cmdline` returns qemu commandline that
doesn't have absolute/complete qemu binary path. when the cmdline is parsed to
virsh domxml-from-native it fails with,

error: Cannot check QEMU binary qemu-system-ppc64: No such file or directory

so handle it to ensure the cmdline have absolute/complete qemu binary path.

Signed-off-by: Balamuruhan S <bala24@linux.vnet.ibm.com>