Fix virtual network pxe boot failure
1. Add missing step for ldlinux.c32 copy
2. Remove the failure of debug output
from get_stripped_output to avoid error
ERROR: [1S is not included in the known console codes list
which is caused in aexpect and not fixed now. please check
https://github.com/avocado-framework/aexpect/pull/48 for detailed info

Signed-off-by: Kylazhang <weizhan@redhat.com>