Fix for aarch64/rhel.guest_os_booting.boot_order.usb_device.hostdev_device Signed-off-by: Slancast1 <slancast@redhat.com>
-- The Issue
A test related to boot_from_usb_device.py would not pass:
guest_os_booting.boot_order.usb_device.hostdev_device

The test would fail with the following error message

LibvirtXMLError: Failed to define avocado-vt-vm1 for reason:error: Failed to define domain from /tmp/xml_utils_temp_l7acogze.xmlerror: unsupported configuration: BIOS serial console only supported on x86 architectures&#10;
This test would not pass for two reasons:
	1) The 'bios_useserial' flag is not compatible with aarch64/edk2
	2) The UEFI prints a different string on aarch64 than it does on other platforms. The test looks at this output, so this is bad.

-- The Fix
        1) Remove the 'bios_useserial' flag from bootmenu_dict in the *.cfg file for aarch64
	2) Redefine check_prompt to include "UsbBootDetectMedia: UsbBootIsUnitReady .*" so the proper message can be detected