Fix restore permission deny
This is to fix the error when exexcuting virsh.restore
error: Failed to open file '/var/tmp/xxx.xml': Permission denied

The root cause is the un-priveledge user has no access to xxx.xml.

Signed-off-by: Dan Zheng <dzheng@redhat.com>