migrate_vm: Fix missing check for stress_type
This will fix the error below for some cases.
AttributeError: 'NoneType' object has no attribute 'split'

Signed-off-by: Dan Zheng <dzheng@redhat.com>