virsh_domblkerror: enable selinux for distro other than ubuntu
This patchset fixes the following,
	- test failed while performing selinux configuration on ubuntu machine
	- nfs service name for ubuntu is nfs-kernel-server
	- UnboundLocalError: local variable 'nfs_service' referenced before assignment
	  for variable in clean up part which is not initialized.

Signed-off-by: Balamuruhan S <bala24@linux.vnet.ibm.com>