passt_function: Don't print "Done" msg to vm session
A json decoding error could happen when parsing the tshark output from
vm session:
json.decoder.JSONDecodeError: Extra data: line 86 column 1 (char 1411)

It is because of the "Done" msg from the exit of tshark in background:
[1]+  Done    tshark -f "udp port 67 or 68 or 546 or 547" -T json -e dhcp.option.hostname -e dhcp.fqdn.name -e dhcpv6.client_domain > dhcp.json

Add disown cmd before the exit of tshark cmd to prevent the msg.

Signed-off-by: Han Han <hhan@redhat.com>