numad_vcpupin: skip cpu not pin
There are some host cpus which can not be pin by default.
Original codes did not test those cpus and directly pin to
those host cpus which causes similar error like below:

error: Unable to write to '/sys/fs/cgroup/cpuset/machine.slice/
machine-qemu\x2d1\x2davocado\x2dvt\x2dvm1.scope/libvirt/
vcpu0/cpuset.cpus': Permission denied

So we need to skip those cpus when testing vcpupin.

Signed-off-by: Dan Zheng <dzheng@redhat.com>