Fix no more available PCI slots for interface device
When hotplug interface, it will use rtl8139 as the default model.
Add this interface device will be plugged into 'pcie-to-pci-bridge'.
If no such controller on guest, the hotplug interface will fail.

For example:
error: Failed to attach interface
error: internal error: No more available PCI slots

If set model to 'virtio', it will succeed. Because it will be
plugged into pcie slot(pcie-root-port).

Signed-off-by: lcheng <lcheng@redhat.com>