pcie_controllers: support auto index
This is to support the newly added controller can be detected with
an index automatically instead of defining a fix number for its index
in order to avoid of below error in future when vm xml is changed.

 error: XML error: Attempted double use of PCI Address 0000:06:00.0"

Signed-off-by: Dan Zheng <dzheng@redhat.com>