virsh_hypervisor_cpu_baseline: skip test on aarch64
aarch64 doesn't support hypervisor_cpu_baseline
```
error: Operation not supported: computing baseline hypervisor CPU is not
supported for arch aarch64
```

Signed-off-by: Liu Yiding <liuyd.fnst@fujitsu.com>