Boot_order: ensure only 1 repo is used to get boot.iso
Issue:
VMStartError: VM 'avocado-vt-vm1' failed to start: error:
Failed to start domain 'avocado-vt-vm1'error: Cannot access storage file
'/var/lib/avocado/data/avocado-vt/boot.iso': No such file or directory(exit status: 1)

Fix:
This issue is caused by multiple repos being fetched and then their urls being concatenated together.
The fix is to ensure that only 1 repo is fetched (the last result),
which can in turn get the boot.iso file.