virsh_domblkerror: Fixup to check nfs package availablity in host
For unspecified_error test would require nfs packages to be installed and
available in host, commit 4f78942 checks and installs in guest which breaks
the test.

Signed-off-by: Junxiang Li <junli@redhat.com>
Signed-off-by: Balamuruhan S <bala24@linux.vnet.ibm.com>