migrate_mem: Fix command error in check_logfile
To fix error as follows:
CmdError: Command 'grep -E 'Unsupported migration cookie feature
 memory-hotplug' /var/log/libvirt/libvirt_daemons.log'
failed.stdout: b''stderr: b''additional_info: None

Because of commit b6a011b7b98e26dbff87cb97a3b7680639241a69, we need
set ignore_status to True in this case.

Signed-off-by: cliping <lcheng@redhat.com>