cpu: Add aarch64_cpu_sve test
SVE is the next-generation SIMD extension of the Arm v8-A AArch64
instruction set.
It  provided it is a multiple of 128 bits and does not exceed the architectural
maximum of 2048 bits.

Each processor may support different vector length. This test works on Fugaku
processor(A64FX) announced to support 512bit.

- Positive test:
    1) Enable sve in domain xml. Expect guest support SVE. The length
       should be sve512 by default
        ```
        <feature policy='require' name='sve'/>
        # Check guest
        [root@localhost ~]# dmesg | grep -i sve
        [    0.010220] SVE: maximum available vector length 64 bytes per vector
        [    0.010229] SVE: default vector length 64 bytes per vector
        ```
    2) Disable sve in domain xml. Expect guest doesn't support SVE
        ```
        <feature policy='disable' name='sve'/>
        # Check guest
        [root@localhost ~]# dmesg | grep -i sve
        [root@localhost ~]#
        ```
    3) Specify single valid sve length. Expect guest SVE available with only
       the selected vector
        E.g.
        ```
        <feature policy='require' name='sve128'/>
        # Check guest
        [root@localhost ~]# dmesg | grep -i sve
        [    0.010042] SVE: maximum available vector length 16 bytes per vector
        [    0.010051] SVE: default vector length 16 bytes per vector
        ```
- Negative test:
    1) Specify invalid sve length sve1234. Expect start guest failed
        ```
        <feature policy='require' name='sve1234'/>
        # Start guest
        [root@fujitsu-fx700-01-n00 ~]# virsh start avocado-vt-vm1
        error: Failed to start domain 'avocado-vt-vm1'
        error: unsupported configuration: unknown CPU feature: sve1234
        ```

Signed-off-by: Liu Yiding <liuyd.fnst@fujitsu.com>