virtual_disks_vhostuser: Set queues of vhost blk to 1
Since QEMU 5.2 (commit a4eef0711b2)[1] the default queues of
vhost-user-blk-pci will be set to the numbers of smp. In case it is over
the default queues value 1 in qemu-storage-daemon, set it to 1.

Fixes the error of the following:
stderr: error: Failed to attach device from /tmp/xml_utils_temp_urlvuc1f.xml
error: internal error: unable to execute QEMU command 'device_add':
vhost initialization failed: Invalid argument

Reference:
[1]: https://gitlab.com/qemu/qemu/-/commit/a4eef0711b2cf7a7476c3e2c202a414b68a1baa0

Signed-off-by: Han Han <hhan@redhat.com>