Exportfs command not found error fixing!
Some tests require "exportfs" command which comes with the nfs-utils package so this patch will install the package, if it can't be installed the test will be cancelled so that the following error won't occur:

Error: Command 'exportfs' could not be found in any of the PATH dirs: ['/bin', '/root/.local/bin', '/root/bin', '/sbin', '/usr/bin', '/usr/libexec', '/usr/local/bin', '/usr/local/sbin', '/usr/sbin', '/usr/share/Modules/bin']
Signed-off-by :Anushree Mathur <anushree.mathur@linux.vnet.ibm.com>