filesystem_device: remove numa cells
The tests fail when numa cells are already
present in the guest xml because vm_xml.set_vm_vcpus
will construct a wrong attributes dict:

[{'xmltreefile': None, 'validates': None, 'xml': <_io.FileIO
name='/tmp/xml_utils_temp_1ju8k73s.xml' mode='rb+' closefd=True>,
'virsh': <module 'virttest.virsh' from
'/var/ci/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/virsh.py'>}]

...leading to error

    TypeError: Attributes values should be str-type of int-type.

Remove the numa cells and leave it to set_vm_vcpus to add them
according to input. It will then create the correct dict

[{'cpus': '0-1', 'id': '0', 'memory': '2097152'}]

Signed-off-by: Sebastian Mitterle <smitterl@redhat.com>