virsh_vol_download_upload: AttributeError: module 'string' has no attribute 'lowercase'
This PR fix two problems:

1) string.lowercase deprecated in python3, and same issue with
string.uppercase.
2) add encode to writing data as file is opened with "wb"

Signed-off-by: Yan Li <yannli@redhat.com>