libvirt autotest vnc ipv6 series case failed
rally defect LIBVIRTAT-3267

test case failed with strange syntax error as follows:

ValueError: invalid interpolation syntax in
'0000:0000:0000:0000:0000:0000:0000:0001%1' at position 39&#10;

expected_result is a list of IPAddress which has a addr attribute.
Therefore, it is correct to use .addr to get correct ipv6 address.

Signed-off-by: Jin Li <jil@redhat.com>