domif_setlink_getlink: fix link state change too fast problem
As set link down command follow behind set link up command, in some
test it got:

  ShellTimeoutError: Timeout expired while waiting for shell command
  to complete: 'ip link set dev eth0 down'

and in output:

  IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready

the cause could be time gap between up and down operation, so use
wait_for_login to confirm the link is up and ready, then set link
down in serial console to avoid this problem.

Signed-off-by: Wayne Sun <gsun@redhat.com>