Python 3: Type error fix for base64
This PR is to fix below issue when with base64 encode and decode:
TypeError: a bytes-like object is required, not 'str'

Signed-off-by: Yan Li <yannli@redhat.com>