virsh_domblkerror: traceback due to using of closed session object
using closed session object cause test to get interrupted, handle it
appropriately by new session and have check to close session on cleanup
if test interrupted after opening session.

Signed-off-by: Balamuruhan S <bala24@linux.vnet.ibm.com>